version: '2'

services:
  haloceded:
    image: augusdogus/haloce
    restart: always
    ports:
      - 2302:2302/udp
      - 2303:2303/tcp
    volumes:
      - /opt/haloce:/game
    environment:
      - PUID=1000
      - PGID=1000
      - RUN_AS_USER=true
